cloud:
  aws:
    credentials:
      access-key: ""
      secret-key: ""
    region:
      static: us-west-1
    stack:
      auto: false

application:
  bucket:
    name: aareeb11imagestorage

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 100MB
      max-file-size: 500MB
      max-request-size: 50MB

server:
  port: 8080
